#!/usr/bin/perl
use IO::Socket::INET;
use LWP::Simple;
use Time::localtime;


# direktes setzen von Werten

$xte = 0.0;
$xpr = 1013;
$xhu = 99.9;
$xws = 100.0;
$xwm = 150.0;
$xwd = 270;
$xwc = 0.0;

print "Zeit:          $xdate $xtime\n";
print "Temperatur:    $xte\n";
print "Luftdruck:     $xpr\n";
print "Feuchte:       $xhu\n";
print "Windspeed cal: $xws\n";
print "Windmax cal:   $xwm\n";
print "Windrichtung:  $xwd\n";
print "windchill:     $xwc\n";


$content = get("http://localhost:81/wetterstation/insert3.php?wd=$xwd&ws=$xws&te=$xte&pr=$xpr&ms=$xwm&hu=$xhu&wc=$xwc&xtsd=$xdate&xtst=$xtime");
print "\nBergrechner: $content";

$content = get("http://wetter:merkur11\@www.schwarzwaldgeier.de/_extphp/wetterstation/insert/insert3.php?wd=$xwd&ws=$xws&te=$xte&pr=$xpr&ms=$xwm&hu=$xhu&wc=$xwc&xtsd=$xdate&xtst=$xtime");
print "GSV Homepage: $content";

