#!/usr/bin/perl -w

#	Build a weather page based on yesterday's data

use strict;

my @dow = qw/Sunday Monday Tuesday Wednesday Thursday Friday Saturday/;
my @mon = qw/January February March April May June July August September October November December/;

my ($wdir, $web);
if (-e "/archive") { # earthman
	$wdir = "/archive/stuff/weatherdata/"; # where are files kept
	$web = "/archive/stuff/weatherdata/Weather/"; # where do we put output?
}
else { # starman
	$wdir = "/home2/archive/weatherdata/"; # where are files kept
	$web = "/home/ajackson/mirrors/icct/weather/"; # where do we put output?
}

#	what is yesterday?

my @yest = localtime(time() - 24*3600);
#my $yesterday = sprintf("%s, %s %d, %d", $dow[$yest[6]], $mon[$yest[4]], $yest[3], 1900+$yest[5]);

#	what is the last datafile?

opendir(DIR,$wdir) || die "Can't open directory $wdir, $!\n";
my @files = readdir(DIR);
my @datafiles = grep (/^arch\d/,@files);
@datafiles = map {s/arch//;$_;} @datafiles;
my $file = (sort {$b<=>$a} @datafiles)[0];
$file = "arch" . $file;

print "File used is $file\n";

#	Create packed file

`Pack_weather.pl $file $wdir`;

#	Yesterday's date is...

my $yesterday = sprintf("%s/%s/%s",$yest[4]+1, $yest[3], 1900+$yest[5]);

#	Create the plots

chdir $wdir;
`/home/ajackson/bin/Wind_plots.pl --fromdate $yesterday --todate $yesterday --prefix yesterday --style tadpole --type minutes`;
`cp yesterday_Wind.png $web`;
`/home/ajackson/bin/Temp_plots.pl --fromdate $yesterday --todate $yesterday --prefix yesterday --type minutes`;
`cp yesterday_Temperature.png $web`;
`cp yesterday_Pressure.png $web`;
`cp yesterday_Humidity.png $web`;
`/home/ajackson/bin/Rain_plots.pl --fromdate $yesterday --todate $yesterday --prefix yesterday --sum_rate rate  --type hourly`;
`cp yesterday_Rain.png $web`;
#my %files;
#for (@files) {$files{$_}=1;}
#foreach (qw/rose_0.png rose_1.png rose_2.png rose_3.png/) {
#	if (! defined $files{$_}) {
#	print STDERR "--> $_\n";
#		system("cp no_wind_data.png $web/$_");
#	}
#}

#	Build the webpage

open (MINMAX,"<$wdir"."yesterday_tmaxmin") || die "Can't open tmaxmin, $!\n";
my @tmm = <MINMAX>;
my $minmax = join('<p>',@tmm);
close MINMAX;

open (WMAX,"<$wdir"."yesterday_wmax") || die "Can't open wmax, $!\n";
my @wmax = <WMAX>;
my $wmax = join('<p>',@wmax);
close WMAX;

open (RAIN,"<$wdir"."yesterday_raintot") || die "Can't open raintot, $!\n";
my @raintot = <RAIN>;
my $raintot = join('<p>',@raintot);
close RAIN;

#open (PRESS,"<$wdir"."press") || die "Can't open press, $!\n";
#my @press = <PRESS>;
#my $press = join('<p>',@press);
#close PRESS;

open (WEB,">$web"."/yesterday.html") || die "Can't open $web yesterday.html, $!\n";
while (<DATA>) {
	if (/%%/) {
		if (/%%yesterday%%/) {
			s/%%yesterday%%/$yesterday/;
		}
		elsif (/%%minmaxt%%/) {
			s/%%minmaxt%%/$minmax/;
		}
		elsif (/%%wmax%%/) {
			s/%%wmax%%/$wmax/;
		}
		elsif (/%%raintot%%/) {
			s/%%raintot%%/$raintot/;
		}
	#	elsif (/%%press%%/) {
	#		s/%%press%%/$press/;
	#	}
	}
	print WEB $_;
}

1;
__DATA__
<html>
<body background="cloud2.jpg">
<h1>Weather from %%yesterday%%, Houston, Texas</h1>
<table bgcolor="black">
<!-- ============ wind =============== -->
<tr><td colspan=6><center><b><font size=+2 color="white">Wind Speed and Direction</font></b></center></td></tr>
<tr><td colspan=6><center>
<img src="yesterday_Wind.png">
</td></tr>
<tr><td colspan=6><center><font size=+1 color="white">%%wmax%%
</font></center></td></tr>
</table>
<!-- ============ Temperature =============== -->
<p>
<table bgcolor="black">
<tr><td><img src="yesterday_Temperature.png"></td></tr>
<tr>
<td>&nbsp;&nbsp;</td>
</tr>
<tr><td><center><font size=+1 color="white">%%minmaxt%%
</font></center></td></tr>
</table>
<!-- ============ Humidity =============== -->
<p>
<table bgcolor="black">
<tr><td><img src="yesterday_Humidity.png"></td></tr>
</tr>
</table>
<!-- ============ Pressure =============== -->
<p>
<table bgcolor="black">
<tr><td><img src="yesterday_Pressure.png"></td></tr>
<tr>
<td>&nbsp;&nbsp;</td>
</tr>
<!--
<tr><td><center><font size=+1 color="white">%%press%%
</font></center></td></tr>
-->
</table>
<!-- ============ Rainfall =============== -->
<p>
<table bgcolor="black">
<tr><td><img src="yesterday_Rain.png"></td></tr>
<tr>
<td>&nbsp;&nbsp;</td>
</tr>
<tr><td><center><font size=+1 color="white">%%raintot%%
</font></center></td></tr>
</table>

</body>
</html>

